name: Flutter Build Production APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Configure Android SDK Level 21
      run: |
        # ক্যামেরা ও এমএল কিটের জন্যSdkVersion বাড়ানো
        sed -i 's/minSdkVersion .*/minSdkVersion 21/' android/app/build.gradle

    - name: Fetch Dependencies
      run: flutter pub get

    - name: Build Release APK
      run: flutter build apk --release

    - name: Upload Generated APK
      uses: actions/upload-artifact@v4
      with:
        name: Token-Scanner-APK
        path: build/app/outputs/flutter-apk/app-release.apk
